import type { DocTable } from "./types.js";

/** Built-in Jinja2 filters. Signatures show the common form; most accept extra arguments. */
export const FILTER_DOCS: DocTable = {
  abs: { signature: "abs(value)", description: "Return the absolute value of a number." },
  attr: { signature: "attr(obj, name)", description: "Get an attribute of an object by name." },
  batch: { signature: "batch(value, linecount, fill_with=None)", description: "Split a sequence into batches of the given size." },
  capitalize: { signature: "capitalize(value)", description: "Capitalize the first character, lowercase the rest." },
  center: { signature: "center(value, width=80)", description: "Center the value in a field of the given width." },
  default: { signature: "default(value, default_value='', boolean=False)", description: "Fall back when the value is undefined (or falsy with boolean=True)." },
  dictsort: { signature: "dictsort(value, case_sensitive=False, by='key')", description: "Sort a dict by key or value." },
  escape: { signature: "escape(value)", description: "Escape HTML special characters." },
  filesizeformat: { signature: "filesizeformat(value, binary=False)", description: "Format a byte count as a human-readable file size." },
  first: { signature: "first(value)", description: "Return the first item of a sequence." },
  float: { signature: "float(value, default=0.0)", description: "Convert the value to a float." },
  forceescape: { signature: "forceescape(value)", description: "Escape HTML, enforcing escaping even on marked-safe values." },
  format: { signature: "format(value, *args, **kwargs)", description: "Apply Python-style string formatting to the value." },
  groupby: { signature: "groupby(value, attribute)", description: "Group a sequence of objects by an attribute." },
  indent: { signature: "indent(value, width=4, first=False, blank=False)", description: "Indent lines after the first by the given width." },
  int: { signature: "int(value, default=0, base=10)", description: "Convert the value to an integer." },
  join: { signature: "join(value, delimiter='')", description: "Join a sequence into a string." },
  last: { signature: "last(value)", description: "Return the last item of a sequence." },
  length: { signature: "length(value)", description: "Return the number of items (alias: count)." },
  list: { signature: "list(value)", description: "Convert the value to a list." },
  lower: { signature: "lower(value)", description: "Convert the value to lowercase." },
  map: { signature: "map(value, filter_or_attribute, ...)", description: "Apply a filter or attribute lookup to every item." },
  max: { signature: "max(value, attribute=None)", description: "Return the largest item." },
  min: { signature: "min(value, attribute=None)", description: "Return the smallest item." },
  pprint: { signature: "pprint(value)", description: "Pretty-print the value for debugging." },
  random: { signature: "random(value)", description: "Return a random item from the sequence." },
  reject: { signature: "reject(value, test, ...)", description: "Reject items matching the test." },
  rejectattr: { signature: "rejectattr(value, attribute, test, ...)", description: "Reject objects whose attribute matches the test." },
  replace: { signature: "replace(value, old, new, count=None)", description: "Replace occurrences of a substring." },
  reverse: { signature: "reverse(value)", description: "Reverse the sequence." },
  round: { signature: "round(value, precision=0, method='common')", description: "Round the number to the given precision." },
  safe: { signature: "safe(value)", description: "Mark the value as safe: skip HTML autoescaping." },
  select: { signature: "select(value, test, ...)", description: "Select items matching the test." },
  selectattr: { signature: "selectattr(value, attribute, test, ...)", description: "Select objects whose attribute matches the test." },
  slice: { signature: "slice(value, slices, fill_with=None)", description: "Slice a sequence into equally sized parts." },
  sort: { signature: "sort(value, reverse=False, case_sensitive=False, attribute=None)", description: "Sort the sequence." },
  string: { signature: "string(value)", description: "Convert the value to a string." },
  striptags: { signature: "striptags(value)", description: "Strip SGML/XML tags from the value." },
  sum: { signature: "sum(value, attribute=None, start=0)", description: "Sum the items, optionally over an attribute." },
  title: { signature: "title(value)", description: "Title-case the value." },
  tojson: { signature: "tojson(value, ...)", description: "Serialize the value to JSON for embedding in scripts." },
  trim: { signature: "trim(value, chars=None)", description: "Strip leading and trailing whitespace." },
  truncate: { signature: "truncate(value, length=255, killwords=False, end='...')", description: "Truncate the string to the given length." },
  unique: { signature: "unique(value, case_sensitive=False, attribute=None)", description: "Remove duplicates, preserving order." },
  upper: { signature: "upper(value)", description: "Convert the value to uppercase." },
  urlencode: { signature: "urlencode(value)", description: "URL-encode a string or mapping." },
  urlize: { signature: "urlize(value, trim_url_limit=None, nofollow=False)", description: "Turn URLs in plain text into links." },
  wordcount: { signature: "wordcount(value)", description: "Count the words in the string." },
  wordwrap: { signature: "wordwrap(value, width=79, break_long_words=True)", description: "Wrap words to the given line width." },
  xmlattr: { signature: "xmlattr(value, autospace=True)", description: "Render a dict as XML/HTML tag attributes." },
};
