import type { DocTable } from "./types.js";

/** Jinja statement keywords and expression operators. End tags close their opener. */
export const KEYWORD_DOCS: DocTable = {
  if: { signature: "{% if condition %} … {% endif %}", description: "Render the body when the condition is truthy." },
  elif: { signature: "{% elif condition %}", description: "Additional condition inside an if block." },
  else: { signature: "{% else %}", description: "Fallback branch of if and for blocks." },
  endif: { signature: "{% endif %}", description: "Closes an if block." },
  for: { signature: "{% for target in iterable %} … {% endfor %}", description: "Loop over each item; exposes the `loop` helper inside." },
  endfor: { signature: "{% endfor %}", description: "Closes a for block." },
  set: { signature: "{% set name = value %}", description: "Assign a template variable (or a block with {% endset %})." },
  endset: { signature: "{% endset %}", description: "Closes a block-set assignment." },
  block: { signature: "{% block name %} … {% endblock %}", description: "Define an overridable region for template inheritance." },
  endblock: { signature: "{% endblock %}", description: "Closes a block." },
  extends: { signature: '{% extends "parent.html" %}', description: "Inherit layout from a parent template." },
  include: { signature: '{% include "partial.html" %}', description: "Render another template in place." },
  import: { signature: '{% import "macros.html" as m %}', description: "Import a template namespace under an alias." },
  from: { signature: '{% from "macros.html" import name %}', description: "Import names from another template." },
  macro: { signature: "{% macro name(args) %} … {% endmacro %}", description: "Define a reusable template function." },
  endmacro: { signature: "{% endmacro %}", description: "Closes a macro definition." },
  call: { signature: "{% call macro(args) %} … {% endcall %}", description: "Call a macro with the block body as `caller`." },
  endcall: { signature: "{% endcall %}", description: "Closes a call block." },
  filter: { signature: "{% filter name %} … {% endfilter %}", description: "Apply a filter to the whole block body." },
  endfilter: { signature: "{% endfilter %}", description: "Closes a filter block." },
  with: { signature: "{% with a=1 %} … {% endwith %}", description: "Render the body with temporary local names." },
  endwith: { signature: "{% endwith %}", description: "Closes a with block." },
  raw: { signature: "{% raw %} … {% endraw %}", description: "Output the body verbatim, without interpreting tags." },
  endraw: { signature: "{% endraw %}", description: "Closes a raw block." },
  do: { signature: "{% do expression %}", description: "Evaluate an expression for side effects, rendering nothing." },
  in: { signature: "target in iterable / value in seq", description: "Loop source, membership test, or `is in` test." },
  is: { signature: "value is test", description: "Apply a builtin test, optionally negated with `not`." },
  not: { signature: "not value", description: "Logical negation (also `is not` and `not in`)." },
  and: { signature: "a and b", description: "Logical conjunction." },
  or: { signature: "a or b", description: "Logical disjunction." },
  true: { signature: "true", description: "Boolean true literal." },
  false: { signature: "false", description: "Boolean false literal." },
  none: { signature: "none", description: "The None literal (undefined-like empty value)." },
  recursive: { signature: "{% for x in y recursive %}", description: "Enable recursive looping via `loop(item)`." },
  scoped: { signature: "{% block name scoped %}", description: "Block modifier: require the block context." },
  as: { signature: "{% import x as y %} / {% from x import a as b %}", description: "Alias an import." },
  without: { signature: "without context", description: "Template modifier: render without the current context." },
  context: { signature: "with(out) context", description: "Template modifier controlling context passing." },
};
