import type { DocTable } from "./types.js";

/** Built-in Jinja2 tests, used with `is` (optionally `is not`). */
export const TEST_DOCS: DocTable = {
  callable: { signature: "value is callable", description: "True if the value can be called." },
  defined: { signature: "value is defined", description: "True if the variable is defined in the context." },
  divisibleby: { signature: "value is divisibleby(num)", description: "True if the value is divisible by num." },
  eq: { signature: "value is eq(other)", description: "True if the value equals other (alias: equalto, ==)." },
  equalto: { signature: "value is equalto(other)", description: "True if the value equals other." },
  escaped: { signature: "value is escaped", description: "True if the value is already escaped markup." },
  even: { signature: "value is even", description: "True if the number is even." },
  false: { signature: "value is false", description: "True if the value is exactly False." },
  filter: { signature: "value is filter(name)", description: "True if a filter with the given name exists." },
  float: { signature: "value is float", description: "True if the value is a float." },
  ge: { signature: "value is ge(other)", description: "True if value >= other (alias: greaterthan)." },
  greaterthan: { signature: "value is greaterthan(other)", description: "True if value > other." },
  gt: { signature: "value is gt(other)", description: "True if value > other." },
  in: { signature: "value is in(seq)", description: "True if the value is contained in the sequence." },
  int: { signature: "value is int", description: "True if the value is an integer." },
  integer: { signature: "value is integer", description: "True if the value is an integer." },
  iterable: { signature: "value is iterable", description: "True if the value can be iterated." },
  le: { signature: "value is le(other)", description: "True if value <= other (alias: lessthan)." },
  lessthan: { signature: "value is lessthan(other)", description: "True if value < other." },
  lower: { signature: "value is lower", description: "True if the string is lowercase." },
  lt: { signature: "value is lt(other)", description: "True if value < other." },
  mapping: { signature: "value is mapping", description: "True if the value is a mapping (dict-like)." },
  ne: { signature: "value is ne(other)", description: "True if the value differs from other." },
  none: { signature: "value is none", description: "True if the value is None." },
  number: { signature: "value is number", description: "True if the value is a number." },
  odd: { signature: "value is odd", description: "True if the number is odd." },
  sameas: { signature: "value is sameas(other)", description: "True if the value is identical to other." },
  sequence: { signature: "value is sequence", description: "True if the value is a sequence (not a string or mapping)." },
  string: { signature: "value is string", description: "True if the value is a string." },
  test: { signature: "value is test(name)", description: "True if a test with the given name exists." },
  true: { signature: "value is true", description: "True if the value is exactly True." },
  undefined: { signature: "value is undefined", description: "True if the value is undefined." },
  upper: { signature: "value is upper", description: "True if the string is uppercase." },
};
